In [51]:
from simple_nmt.data_loader import DataLoader
import simple_nmt.data_loader as data_loader


loader = DataLoader(train_fn='./corpus/sampling.train'
                    ,valid_fn='./corpus/sampling.valid'
                    ,exts = ('en', 'ko')
                    ,batch_size=256
                    ,device=-1
                    ,max_length=256
                    ,dsl=False)


In [52]:
print(len(loader.src.vocab))
print(len(loader.tgt.vocab))

2454
2650


In [53]:
import torch
saved_data = torch.load('./2021.1004.TFM/Transformer.pth',map_location='cpu')
src_vocab = saved_data['src_vocab']
tgt_vocab = saved_data['tgt_vocab']
print(len(src_vocab))
print(len(tgt_vocab))

14000
29579


In [54]:
# for batch in loader.train_iter:
#     print(len(batch.src))
#     x = batch.src[0]
#     lengths = batch.src[1] 
#     print(lengths)
#     y = batch.tgt[0]
#     y = y[0,:]
#     print(y)


In [55]:
# for batch in loader.train_iter:
#     print(len(batch.tgt))
#     x = batch.tgt[0]
#     lengths = batch.tgt[1]
#     print(lengths)

In [56]:
print(loader.src.vocab.itos[0:10])
print(loader.tgt.vocab.itos[0:10])

['<unk>', '<pad>', '▁▁the', '▁,', '▁.', '▁▁of', '▁▁and', '▁▁to', '▁▁a', '▁▁in']
['<unk>', '<pad>', '<BOS>', '<EOS>', '▁.', '▁이', '▁는', '▁을', '▁다', '▁에']


In [57]:
import torch

f = torch.FloatTensor(5,5)
f.cuda()

tensor([[1.0839e-08, 2.6707e-06, 6.7872e-07, 1.2470e+16, 2.1707e-18],
        [7.0952e+22, 1.7748e+28, 1.8176e+31, 7.2708e+31, 5.0778e+31],
        [3.2608e-12, 1.7728e+28, 7.0367e+22, 2.1715e-18, 1.7282e-04],
        [4.1028e-08, 4.2186e-08, 6.7121e-07, 1.6518e-04, 1.0311e-11],
        [2.6562e+20, 1.3400e-08, 4.2095e+21, 2.1707e-18, 7.1450e+31]],
       device='cuda:0')

In [58]:
torch.ones(10)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [59]:
x = torch.tensor([3,4.,7,9])
sm = torch.nn.Softmax(dim=-1)
lsm = torch.nn.LogSoftmax(dim=-1)
print(sm(x))
print(lsm(x))

print(torch.exp(lsm(x)).sum())

tensor([0.0022, 0.0059, 0.1182, 0.8737])
tensor([-6.1350, -5.1350, -2.1350, -0.1350])
tensor(1.)


In [60]:
lr_decay_start = 10
init_epoch = 9
n_epochs = 10
lr_step = 1
m = [i for i in range(
                max(0, lr_decay_start - 1),
                n_epochs,
                lr_step
            )]
print(m)
print(len(m))

[9]
1


In [61]:

with open('./corpus/10_sampling.test.en', 'rt', encoding='utf-8') as file:
    lines = file.readlines()

print(len(lines))
print(lines)

5
['▁▁At ▁▁that ▁▁time ▁, ▁▁the ▁▁medical ▁▁st aff ▁▁of ▁▁B ▁▁h osp ital ▁▁dec ided ▁▁to ▁▁tr eat ▁▁with ▁▁p neum onia ▁▁through ▁▁high ▁- ▁res olution ▁▁comp uted ▁▁t om ography ▁▁of ▁▁the ▁▁ch est ▁, ▁▁b ut ▁▁A ▁▁w as ▁▁not ▁▁c ured ▁. \n', '▁▁If ▁▁the ▁▁or dinance ▁▁g oes ▁▁in to ▁▁eff ect ▁, ▁▁the ▁▁Mayor ▁▁of ▁▁Seoul ▁▁can ▁▁res trict ▁▁the ▁▁operation ▁▁of ▁▁v ehic les ▁▁rated ▁▁f if th ▁- ▁grade ▁▁em issions ▁▁if ▁▁em ergency ▁▁r eduction ▁▁m easures ▁▁for ▁▁fine ▁▁d ust ▁▁are ▁▁issued ▁. \n', '▁▁After ▁▁coll ecting ▁▁v arious ▁▁op in ions ▁▁through ▁▁disc ussion ▁▁s essions ▁▁and ▁▁o thers ▁, ▁▁Gwangju ▁▁M etropolitan ▁▁Government ▁▁will ▁▁come ▁▁up ▁▁with ▁▁m easures ▁▁to ▁▁prev ent ▁▁the ▁▁rec kless ▁▁construction ▁▁of ▁▁high ▁- ▁rise ▁▁apar tments ▁▁in ▁▁d ow n town ▁▁Gwangju ▁. \n', "▁▁S av ory ▁▁s o yb ean ▁▁n oodles ▁, ▁▁if ▁▁ever yone ▁' ▁s ▁▁up ▁▁for ▁▁it ▁, ▁▁let ▁' ▁s ▁▁go ▁. \n", '▁▁More ▁▁than ▁▁two ▁▁hours ▁▁after ▁▁taking ▁▁off ▁, ▁▁the ▁▁cap tain ▁▁of ▁▁the ▁▁pri

In [62]:
y = torch.LongTensor([i for i in range(10)])
mask = y.new_ones(y.size())
mask[2] = 0
mask[8] = 0
mask[4] = 0


print(y)
print(mask)

y = y.masked_fill(mask, 3)
print(y)


y = y * torch.ne(y, 3)
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([1, 1, 0, 1, 0, 1, 1, 1, 0, 1])
tensor([3, 3, 2, 3, 4, 3, 3, 3, 8, 3])
tensor([0, 0, 2, 0, 4, 0, 0, 0, 8, 0])


In [63]:
x = [torch.FloatTensor([.0] + [-float('inf')] * (5 - 1)).to('cpu')]
print(x)

xx = torch.FloatTensor([-float('inf')for i in range(5)])
xx[0] = 0.
print(xx)

[tensor([0., -inf, -inf, -inf, -inf])]
tensor([0., -inf, -inf, -inf, -inf])


In [64]:
word_indice = [torch.LongTensor(5).zero_().to('cuda:0') + 2]
print(word_indice)
w = word_indice[-1].unsqueeze(-1)
print(w)

[tensor([2, 2, 2, 2, 2], device='cuda:0')]
tensor([[2],
        [2],
        [2],
        [2],
        [2]], device='cuda:0')


In [65]:
indice = torch.tensor([1,2,3,4,5,6])
indice.fmod(5)

tensor([1, 2, 3, 4, 0, 1])

In [66]:
import torch.nn as nn

input = torch.randn(10)
print(input)
m = nn.LayerNorm(input.size())
print(m)

y = (m(input))

print(y)

tensor([-0.1722, -0.1759,  0.7157,  0.2741, -0.6753,  0.6818,  2.5599, -1.1975,
         1.7331,  1.8950])
LayerNorm((10,), eps=1e-05, elementwise_affine=True)
tensor([-0.6463, -0.6496,  0.1333, -0.2544, -1.0880,  0.1035,  1.7526, -1.5465,
         1.0266,  1.1688], grad_fn=<NativeLayerNormBackward>)


In [67]:
m = nn.Dropout(p=0.2)
input = torch.randn(4, 10)
output = m(input)
print(output)

tensor([[-1.5159,  0.0077,  0.0000, -0.0000,  1.8641,  0.0000, -0.5543,  1.6411,
         -0.4542, -0.3504],
        [ 0.0000, -1.2326,  0.5883,  1.8005, -0.0395, -0.0990, -0.2354, -0.3119,
          0.8856, -0.0000],
        [ 0.0838, -2.4477, -1.2845, -0.1548, -0.0000,  0.0000, -2.3774,  0.1865,
          0.4781, -0.6468],
        [ 1.3059, -0.0000, -2.1779,  1.5074,  0.0000,  1.2291,  1.5386, -0.0776,
         -0.8262,  0.7273]])


In [68]:

fm = torch.triu(input.new_ones(*input.size()), diagonal=1).bool()
print(fm)

tensor([[False,  True,  True,  True,  True,  True,  True,  True,  True,  True],
        [False, False,  True,  True,  True,  True,  True,  True,  True,  True],
        [False, False, False,  True,  True,  True,  True,  True,  True,  True],
        [False, False, False, False,  True,  True,  True,  True,  True,  True]])


In [69]:
fns = '/2021.0930.TFM/Transformer.pth'.split('/')
fns = fns[:-1]
fns

['', '2021.0930.TFM']

In [70]:
d = {'loss':1000 , 'ppl':999}
for key in d.keys():
    print(d[key])
    

1000
999


In [71]:
z = torch.LongTensor(2,2,2)

print(z[0:1].unsqueeze(0).shape)

torch.Size([1, 1, 2, 2])


In [72]:
pos = torch.arange(0, 512).unsqueeze(-1).float()
dim = torch.arange(0, 768 // 2).unsqueeze(0).float()
dim = (1e+4**dim.div(float(768)))
pos = pos / dim
print(pos.shape)
print(pos[1,-1])

print(dim.shape)
print(dim[0,:10])


torch.Size([512, 384])
tensor(0.0101)
torch.Size([1, 384])
tensor([1.0000, 1.0121, 1.0243, 1.0366, 1.0491, 1.0618, 1.0746, 1.0876, 1.1007,
        1.1140])


In [73]:
x = torch.Tensor([1,1,1,1,1,0.5,0.5,1.5,1.5,1])
sm = torch.nn.Softmax(dim=-1)
print(sm(x))
lsm = torch.nn.LogSoftmax(dim=-1)
x = lsm(x)
print(x)
x = x.view(1,-1)

print(x)
y = torch.LongTensor([7])
l = torch.nn.functional.nll_loss(x,y,reduction='none')
print(l)


tensor([0.0951, 0.0951, 0.0951, 0.0951, 0.0951, 0.0577, 0.0577, 0.1569, 0.1569,
        0.0951])
tensor([-2.3524, -2.3524, -2.3524, -2.3524, -2.3524, -2.8524, -2.8524, -1.8524,
        -1.8524, -2.3524])
tensor([[-2.3524, -2.3524, -2.3524, -2.3524, -2.3524, -2.8524, -2.8524, -1.8524,
         -1.8524, -2.3524]])
tensor([1.8524])


In [74]:
flag = False
x, y = (100, 150) if flag else (200, 250)
print(x)
print(y)

200
250


In [75]:
import pprint
class Args():
    def __init__(self):
        self.a = 10
        self.b = 20
        self.c = 30
        self.d = 40
        self.e = 80

arg = Args()
pp = pprint.PrettyPrinter(indent=4)
pp.pprint(vars(arg))



{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 80}
